---
title: "fitting"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fitting}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

- Fit a distribution with smart defaults. Simple wrapper with little options available for now, but the package has big goals.

- The use of the thin wrappers like `fit_dst_gev()` are also useful because they tell you what `methods` are available.
- Failure cascade:
  - First, missing data handling (`na_action`).
  - Then, fitting failure handling (`on_unres`).
- The behaviour of the lmom fitdistrplus ismev packages are kept when making their specific wrappers.
  - Example: `stop` when fitting fails:
    - "distribution not implemented" is the same as a distribution always failing to fit, and therefore a deliberate `stop()` command has been added for these cases.
    - The case of incompatible parameters / L-moments also throws an error, although these will never be triggered from the user perspective because of the preliminary check that the data is compatible with some supports of the family.
      - The manual ones are tested explicitly, though.
  - Example: when parameters are valid, but results in the data not belonging to the distribution's support, the distribution is still returned. e.g., Uniform distribution.
  
- When calling fitdistrplus::fitdist(), defaults are used except where specified here otherwise (I think just `start` values). There are no options to change other arguments at the moment; if you need that level of control, for now you can call fitdistrplus directly and then make a distionary distribution from the parameters.

- Warning happens when a distribution is not supported.

- Why some combinations are not supported:
  - "mse": the estimate does not appear to be consistent (i.e. does not converge to the true parameter as sample size increases) for many distributions, and is therefore excluded.
  
- Note to self: gumbel fit by mge is not included because didn't want to export p/d/q gumbel functions. When done in distionary, can add it back in.

- Testing:
  - Same test for each method.
  - Failures:
    - Data that deliberately trips up the fitting process: e.g., incompatible moments; support issues (either before or after fitting).
    - Method-distribution pairs that do not exist.
    - FOR EACH: check the correct failure behaviour (error vs warning + null distribution).
  - Check convergence to within a specified tolerance of the actual parameters. If tolerance is not reached, increase sample size, but only up to a point. Sometimes fitting fails because the algorithm fails (even after adding more data), but four seeds are used, and at least one is required to pass. Speed of convergence is not tolerated: manual tolerance level can be used in some cases where the parameter is difficult to estimate (like a high df in a Student t distribution).
- Successfully resolving a distribution under four different datasets that were not taken from the distribution, as a stress test to ensure the fitting still resolves to a distribution.
- Four different seeds ensures that convergence to within tolerance is less likely to be a fluke.
- Checking that the parameter estimation is valid: that the estimates are close to the true parameters (generate more data if needed to get closer).
- Most distributions in distionary are covered, except for hypergeometric.
- To make make the fitting more hands-off, smart starting points for the parameters are used by moment matching where possible (and where starting values are needed by fitdistrplus).
- The most flexible fitting package is fitdistrplus, and is fallen back on. Other wrapped packages include lmom (for l-moments based estimation) and ismev (for MLE estimation of the GEV and GP distributions).
- Support for fitting a Gumbel distribution is also included as a GEV with shape parameter = 0. Family name is "gumbel".

- scoring functions (uscore, etc) are included so you can compare the fitted distribution with empirical scores.

TO DO:

- Family wrappers: complete list and ensure proper methods are included.
- What should I do about the need to fit LP3 by l-moments to its log? Probably make a new `method`, I think.